spring:
  application:
    name: ds1103-ex-usuarios
  #profiles:
  #  active: dev
  datasource:
    url: jdbc:postgresql://35.223.30.52:5432/he_verac_db
    username: he.verac
    password: dsy1103
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: "/doc/swagger-ui.html"

server:
  port: 8083

ventas-api-url: http://localhost:8080/ventas/
usuarios-api-url: http://localhost:8081/usuarios/
pagos-api-url: http://localhost:8082/pagos/
envios-api-url: http://localhost:8084/envios/